SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d") as SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT FROM ONLINE_SALE
where DATE_FORMAT(SALES_DATE,"%Y-%m") = "2022-03"
UNION
SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d") as SALES_DATE,PRODUCT_ID,NULL AS USER_ID,SALES_AMOUNT FROM OFFLINE_SALE
where DATE_FORMAT(SALES_DATE,"%Y-%m") = "2022-03"
order by SALES_DATE asc, PRODUCT_ID asc,USER_ID asc ;