-- 코드를 입력하세요
SELECT WAREHOUSE_ID,WAREHOUSE_NAME,ADDRESS,
CASE WHEN FREEZER_YN IS NULL or FREEZER_YN ="N" then "N" ELSE "Y" END AS FREEZER_YN from FOOD_WAREHOUSE where ADDRESS LIKE "경기도%" order by WAREHOUSE_ID asc;